- name: Add gpg key of docker repo
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  environment:
    - http_proxy: http://10.32.16.22:3128
    - https_proxy: http://10.32.16.22:3128
    - no_proxy: "10.32.15.190,.1rstwap.com,127.0.0.1,localhost"

- name: Copy docker repo to /etc/apt/sources.list.d directory
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list owner=root group=root mode=0644

- name: Update apt repository cache
  apt: update_cache=yes
  environment: "{{ proxy_env }}"
  ignore_errors: yes

# - name: configure dpkg
#   shell: dpkg --configure -a
#   ignore_errors: yes

- name: Install dependencies
  apt: name={{ item }} state=latest force=yes
  environment: "{{ proxy_env }}"
  with_items: "{{ required_package }}"

- name: Install python-docker
  pip: name=docker-py version=1.9.0
  environment: "{{ proxy_env }}"

- name: Remove older binary if exists
  apt: name={{ item }} state=absent
  with_items: "{{ remove_package }}"
  ignore_errors: yes

- name: Install docker engine
  apt: name={{ item }} state=latest force=yes
  environment: "{{ proxy_env }}"
  with_items: "{{ dockers }}"

- name: Override default docker configuration
  template:
    src: docker.j2
    dest: /etc/default/docker
    mode: 0644
    owner: root
    group: root

- name: Get username of the PC
  # command: bash -c "/bin/hostname | awk -F '-' '{print $1}' "
  command: bash -c "ps auxwww | grep xfce4-session | grep -v grep | awk '{ print $1 }'"
  ignore_errors: yes
  changed_when: false
  register: docker_username

- name: Create docker group
  group: name=docker  state=present

- name: Push sudoer config for docker user
  template:
    src: sudoer.j2
    dest: /etc/sudoers.d/docker
    owner: root
    group: root
    mode: 0600

- name: Pull docker image from registry
  docker_image:
    name: "{{ docker_registry }}:{{ registry_port }}/centos"
  ignore_errors: yes

- name: Push docker start wrapper to /usr/bin
  template:
    src: exec/docker-php.j2
    dest: /usr/bin/docker-php
    owner: root
    group: root
    mode: 0755

- name: Push docker stop wrapper to /usr/bin
  copy:
    src: exec/docker-stop-php
    dest: /usr/bin/docker-stop-php
    owner: root
    group: root
    mode: 0755